### ISSUE TITLE
Tautulli iocage jail fails to install on FreeNAS

### ISSUE THREAD

**Issue by spitfire** [arcooke/iocage-plugin-tautulli#2]
when trying to install it on FreeNAS, I'm getting the following error:
`Error: tautulli01 had a failure Exception: RuntimeError Message: Last 10 lines: jexec: execvp: /root/post_install.sh: Permission denied Partial plugin destroyed`

[is post_install.sh executable? ](https://github.com/arcooke/iocage-plugin-tautulli/pull/1)

[Bug report on FreeNAS jira](https://jira.ixsystems.com/browse/NAS-104529)

**Comment by arcooke** [comment]
Thanks for letting me know.  Fixed in https://github.com/arcooke/iocage-plugin-tautulli/commit/fcbe58a7910d4c1692b9e7a42e20a994b4d78d54.  It worked fine when installed locally, didn't notice an issue.
